Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -75,8 +75,8 @@ jobs:
       - name: Proof it exists
         shell: pwsh
         run: |
-          echo [System.IO.File]::Exists('${{ github.workspace }}/bin/XPSystem-nw.dll')
-          echo [System.IO.File]::Exists('${{ github.workspace }}/bin/XPSystem-EXILED.dll')
+          echo $([System.IO.File]::Exists('${{ github.workspace }}/bin/XPSystem-nw.dll'))
+          echo $([System.IO.File]::Exists('${{ github.workspace }}/bin/XPSystem-EXILED.dll'))
 
       - name: Get branch name
         shell: bash
@@ -119,8 +119,8 @@ jobs:
       - name: Proof it exists 2
         shell: pwsh
         run: |
-          echo [System.IO.File]::Exists('${{ github.workspace }}/bin/XPSystem-nw.dll')
-          echo [System.IO.File]::Exists('${{ github.workspace }}/bin/XPSystem-EXILED.dll')
+          echo $([System.IO.File]::Exists('${{ github.workspace }}/bin/XPSystem-nw.dll'))
+          echo $([System.IO.File]::Exists('${{ github.workspace }}/bin/XPSystem-EXILED.dll'))
 
       - uses: ncipollo/release-action@v1.13.0
         if: ${{ env.newversion == 'true' }}
@@ -139,7 +139,7 @@ jobs:
 
       - name: Create release pr
         if: ${{ env.newversion == 'true' && steps.get_branch.outputs.branch == 'master' }}
-        shell: pwsh
-        run: gh pr create -B release -H master --title '${{ env.currver }}' --body 'Automated PR' -ErrorAction SilentlyContinue
+        shell: bash
+        run: gh pr create -B release -H master --title '${{ env.currver }}' --body 'Automated PR' || echo 'error'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
